//VARIAVEL DA VPC10 QUE ESTA SENDO PEGO DO ORQUESTRADOR E O ORQUESTRADOR ESTA PEGANDO DO PROPRIO OVARS.TF
variable "vpc10_roro" {}

//VARIAVEL DA VPC10 QUE ESTA SENDO PEGO DO ORQUESTRADOR E O ORQUESTRADOR ESTA PEGANDO DO OUTPUT.TF DO MODULO NETWORK
variable "vpc10_id" {}

//VARIAVEL DA VPC20 QUE ESTA SENDO PEGO DO ORQUESTRADOR E O ORQUESTRADOR ESTA PEGANDO DO PROPRIO OVARS.TF
variable "vpc20_tchutchu" {}

//VARIAVEL DA VPC20 QUE ESTA SENDO PEGO DO ORQUESTRADOR E O ORQUESTRADOR ESTA PEGANDO DO OUTPUT.TF DO MODULO NETWORK
variable "vpc20_id" {} 

//VARIAVEL DA SUBNET PUBLICA DA AZ1A DA VPC10 QUE ESTA SENDO PEGO DO ORQUESTRADOR
// E O ORQUESTRADOR ESTA PEGANDO DO OUTPUT.TF DO MODULO NETWORK
variable "vpc10_sn_pub_az1a_id" {}

//VARIAVEL DA SUBNET PRIVADA DA AZ1C DA VPC10 QUE ESTA SENDO PEGO DO ORQUESTRADOR
// E O ORQUESTRADOR ESTA PEGANDO DO OUTPUT.TF DO MODULO NETWORK
variable "vpc10_sn_priv_az1c_id" {}  

//VARIAVEL DA SUBNET PUBLICA DA AZ1A DA VPC20 QUE ESTA SENDO PEGO DO ORQUESTRADOR
// E O ORQUESTRADOR ESTA PEGANDO DO OUTPUT.TF DO MODULO NETWORK
variable "vpc20_sn_pub_az1a_id" {}

//VARIAVEL DA SUBNET PRIVADA DA AZ1C DA VPC20 QUE ESTA SENDO PEGO DO ORQUESTRADOR
// E O ORQUESTRADOR ESTA PEGANDO DO OUTPUT.TF DO MODULO NETWORK
variable "vpc20_sn_priv_az1c_id" {}
  

  

