name: IaC Backend

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/provider.tf'
    - '.github/workflows/iac-backend.yaml'

jobs:

  job-Terraform_Backend:
    runs-on: ubuntu-latest
 
    steps:

    - name: Step 01 - Set AWS Account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token    : ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region           : ${{ vars.AWS_REGION }}

    - name: Step 02 - Set S3 Bucket
      run: |
        aws s3api create-bucket --bucket ${{ vars.AWS_S3_BUCKET }} --region ${{ vars.AWS_REGION }}
