name: IaC Backend

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/provider.tf'
    - '.github/workflows/iac-backend.yaml'

jobs:

  job-Terraform_Backend:
    runs-on: ubuntu-latest
    env :
      AWS_REGION_DEFAULT: "us-east-2"
 
    steps:

    - name: Step 01 - Set AWS Account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token    : ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region           : ${{ vars.AWS_REGION }}

    - name: Step 02 - Set S3 Bucket
      run: |
        echo "AWS_REGION = ${{ vars.AWS_REGION }}"
        echo "AWS_REGION_DEFAULT = $AWS_REGION_DEFAULT"
        # aws s3api create-bucket --bucket ${{ env.AWS_S3_BUCKET }} --region ${{ env.AWS_REGION }}
