name: Terraform Backend Setup

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/terraform-backend-setup.yaml'

jobs:

  job-Terraform_Backend_Setup:
    runs-on: ubuntu-latest
 
    steps:

    - name: Step 01 - Set AWS Account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token    : ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region           : ${{ vars.AWS_REGION }}

    - name: Step 02 - Set S3 Bucket
      run: |
        if aws s3api head-bucket --bucket ${{ vars.AWS_S3_BUCKET }} 2>/dev/null; then
          echo "S3 bucket '${{ vars.AWS_S3_BUCKET }}' found"
        else 
          echo "Creating S3 bucket '${{ vars.AWS_S3_BUCKET }}' ..."
          aws s3api create-bucket \
            --bucket ${{ vars.AWS_S3_BUCKET }}
          # aws s3api put-bucket-versioning \
          #   --bucket ${{ vars.AWS_S3_BUCKET }} \
          #   --versioning-configuration \
          #     MFADelete=Disabled,Status=Enabled
        fi

    - name: Step 03 - Set DynamoDB Table
      run: |
        if aws dynamodb describe-table --table-name ${{ vars.AWS_DYNAMODB_TABLE }} 2>/dev/null; then
          echo "DynamoDB table '${{ vars.AWS_DYNAMODB_TABLE }}' found"
        else 
          echo "Creating DynamoDB table '${{ vars.AWS_DYNAMODB_TABLE }}' ..."
          aws dynamodb create-table \
            --table-name ${{ vars.AWS_DYNAMODB_TABLE }} \
            --attribute-definitions \
              AttributeName=LockID,AttributeType=S \
            --key-schema \
              AttributeName=LockID,KeyType=HASH \
            --provisioned-throughput \
              ReadCapacityUnits=1,WriteCapacityUnits=1
        fi
